// 예외가 발생했을 때 실행되는 이벤트
process.on('uncaughtException', function (err) {

});
